### ISSUE TITLE
div'атоз

### ISSUE THREAD

**Issue by a-merezhanyi** [andreyKuzmin-lehamed/andreyKuzmin-lehamed.github.io#1]
@andreyKuzmin-lehamed Привет. Как можно добраться до исходников, чтобы ПР сделать? Сплошной "диватоз" (термин Макеева). Готов помочь. Где исходники?
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/2270509/155800061-bef65a10-d10e-4613-8083-0ca2dfc73c91.png">
Мы ведь про образование джунов, да?
(если был излишне груб - сорри, прошу сказать - исправлюсь)

**Comment by andreyKuzmin-lehamed** [comment]
Привет, это черновая версия собранная за час на коленке, портал будет
нормально переписываться и тогда я с удовольствием буду принимать помощь. А
пока это не так важно, как просто дать доступ к нужной информации, чтобы
запустить проект.

пт, 25 февр. 2022 г., 14:46 Tolik Merezhanyi ***@***.***>:
